replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/project-41544a08-ca3f-4ea2-8ab/devops-repo/app
  tag: v3
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true
  name: ""

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"